FROM debian:buster

WORKDIR /root

RUN apt-get update \
    && apt-get install unzip -y

ADD https://komodochess.com/pub/komodo-12.zip /root
RUN unzip komodo-12.zip

FROM crissilvaeng/chess-arena-engine:latest

COPY --from=0 /root/komodo-12.*/Linux/komodo-*-linux /usr/bin/komodo

ENV ENGINE_PATH /usr/bin/komodo

WORKDIR /root

CMD ["yarn", "start:prod"]
