FROM debian:buster

WORKDIR /app

RUN apt-get update \
    && apt install build-essential curl -y --no-install-recommends

ADD https://github.com/official-stockfish/Stockfish/archive/sf_13.tar.gz /app
RUN tar xvzf *.tar.gz && cd Stockfish-sf_13/src \
    && make net && make build ARCH=x86-64-modern

FROM docker.io/crissilvaeng/yifan-engine:0.1.0

COPY --from=0 /app/Stockfish-sf_13/src/stockfish /usr/bin/stockfish

WORKDIR /app

ENV ENGINE_PATH /usr/bin/stockfish

CMD [ "yarn", "start" ]
