FROM debian:buster

WORKDIR /app

RUN apt-get update \
    && apt-get install unzip -y

ADD https://komodochess.com/pub/komodo-12.zip /app
RUN unzip komodo-12.zip

FROM docker.io/crissilvaeng/yifan-engine:0.3.0

COPY --from=0 /app/komodo-12.*/Linux/komodo-*-linux /usr/bin/komodo

WORKDIR /app

ENV ENGINE_PATH /usr/bin/komodo

RUN yarn build

CMD [ "yarn", "start:prod" ]