FROM debian:buster

WORKDIR /root

RUN apt-get update \
    && apt install build-essential curl -y --no-install-recommends

ADD https://github.com/official-stockfish/Stockfish/archive/sf_13.tar.gz /root
RUN tar xvzf *.tar.gz && cd Stockfish-sf_13/src \
    && make net && make build ARCH=x86-64-modern

FROM crissilvaeng/chess-arena-engine:latest

COPY --from=0 /root/Stockfish-sf_13/src/stockfish /usr/bin/stockfish

ENV ENGINE_PATH /usr/bin/stockfish

WORKDIR /root

CMD ["yarn", "start:prod"]
